version: '3.9'

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: pgkeycloak
      POSTGRES_PASSWORD: pgpassword

  keycloak:
    image: jboss/keycloak:16.1.0
    depends_on:
      - "postgres"
    environment:
      DB_VENDOR: postgres
      DB_PORT: 5432
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: pgkeycloak
      DB_SCHEMA: public
      DB_PASSWORD: pgpassword
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: locals